apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: pod
  labels:
    env: test
spec:
  replicas: 2
  selector:
    matchLabels:
      tier: pod
  template:
    metadata:
      labels:
        tier: pod
    spec:
      containers:
      - name: web
        image: elistratovvm/web:1.0.0
        imagePullPolicy: IfNotPresent